# Some Default and Mostly Used User-Format to System-Format Datetime Mapping
datetime_mapping = {
    'yyyy-MM-dd-HH': '%Y-%m-%d-%H',
    'dd-MM-yyyy HH:mm:ss.sss': '%d-%m-%Y %H:%M:%S.%f',
    'dd-MM-yyyy-HH:mm:ss.sss': '%d-%m-%Y-%H:%M:%S.%f',
    'dd-MM-yyyy HH:mm:ss': '%d-%m-%Y %H:%M:%S',
    'dd-MM-yyyy-HH:mm:ss': '%d-%m-%Y-%H:%M:%S',
    'dd-MM-yyyy HH:mm': '%d-%m-%Y %H:%M',
    'dd-MM-yyyy-HH:mm': '%d-%m-%Y-%H:%M',
    'dd-MM-yyyy': '%d-%m-%Y',
    'dd-MM-yy HH:mm:ss.sss': '%d-%m-%y %H:%M:%S.%f',
    'dd-MM-yy-HH:mm:ss.sss': '%d-%m-%y-%H:%M:%S.%f',
    'dd-MM-yy HH:mm:ss': '%d-%m-%y %H:%M:%S',
    'dd-MM-yy-HH:mm:ss': '%d-%m-%y-%H:%M:%S',
    'dd-MM-yy HH:mm': '%d-%m-%y %H:%M',
    'dd-MM-yy-HH:mm': '%d-%m-%y-%H:%M',
    'dd-MM-yy': '%d-%m-%y',
    'yyyy-MM-dd HH:mm:ss.sss': '%Y-%m-%d %H:%M:%S.%f',
    'yyyy-MM-dd-HH:mm:ss.sss': '%Y-%m-%d-%H:%M:%S.%f',
    'yyyy-MM-dd HH:mm:ss': '%Y-%m-%d %H:%M:%S',
    'yyyy-MM-dd-HH:mm:ss': '%Y-%m-%d-%H:%M:%S',
    'yyyy-MM-dd HH:mm': '%Y-%m-%d %H:%M',
    'yyyy-MM-dd-HH:mm': '%Y-%m-%d-%H:%M',
    'yyyy-MM-dd': '%Y-%m-%d',
    'yy-MM-dd HH:mm:ss.sss': '%y-%m-%d %H:%M:%S.%f',
    'yy-MM-dd-HH:mm:ss.sss': '%y-%m-%d-%H:%M:%S.%f',
    'yy-MM-dd HH:mm:ss': '%y-%m-%d %H:%M:%S',
    'yy-MM-dd-HH:mm:ss': '%y-%m-%d-%H:%M:%S',
    'yy-MM-dd HH:mm': '%y-%m-%d %H:%M',
    'yy-MM-dd-HH:mm': '%y-%m-%d-%H:%M',
    'yy-MM-dd': '%y-%m-%d',
    'MM-dd-yyyy HH:mm:ss.sss': '%m-%d-%Y %H:%M:%S.%f',
    'MM-dd-yyyy-HH:mm:ss.sss': '%m-%d-%Y-%H:%M:%S.%f',
    'MM-dd-yyyy HH:mm:ss': '%m-%d-%Y %H:%M:%S',
    'MM-dd-yyyy-HH:mm:ss': '%m-%d-%Y-%H:%M:%S',
    'MM-dd-yyyy HH:mm': '%m-%d-%Y %H:%M',
    'MM-dd-yyyy-HH:mm': '%m-%d-%Y-%H:%M',
    'MM-dd-yyyy': '%m-%d-%Y',
    'MM-dd-yy HH:mm:ss.sss': '%m-%d-%y %H:%M:%S.%f',
    'MM-dd-yy-HH:mm:ss.sss': '%m-%d-%y-%H:%M:%S.%f',
    'MM-dd-yy HH:mm:ss': '%m-%d-%y %H:%M:%S',
    'MM-dd-yy-HH:mm:ss': '%m-%d-%y-%H:%M:%S',
    'MM-dd-yy HH:mm': '%m-%d-%y %H:%M',
    'MM-dd-yy-HH:mm': '%m-%d-%y-%H:%M',
    'MM-dd-yy': '%m-%d-%y',
    'dd/MM/yyyy HH:mm:ss.sss': '%d/%m/%Y %H:%M:%S.%f',
    'dd/MM/yyyy-HH:mm:ss.sss': '%d/%m/%Y-%H:%M:%S.%f',
    'dd/MM/yyyy HH:mm:ss': '%d/%m/%Y %H:%M:%S',
    'dd/MM/yyyy-HH:mm:ss': '%d/%m/%Y-%H:%M:%S',
    'dd/MM/yyyy HH:mm': '%d/%m/%Y %H:%M',
    'dd/MM/yyyy-HH:mm': '%d/%m/%Y-%H:%M',
    'dd/MM/yyyy': '%d/%m/%Y',
    'dd/MM/yy HH:mm:ss.sss': '%d/%m/%y %H:%M:%S.%f',
    'dd/MM/yy-HH:mm:ss.sss': '%d/%m/%y-%H:%M:%S.%f',
    'dd/MM/yy HH:mm:ss': '%d/%m/%y %H:%M:%S',
    'dd/MM/yy-HH:mm:ss': '%d/%m/%y-%H:%M:%S',
    'dd/MM/yy HH:mm': '%d/%m/%y %H:%M',
    'dd/MM/yy-HH:mm': '%d/%m/%y-%H:%M',
    'dd/MM/yy': '%d/%m/%y',
    'yyyy/MM/dd HH:mm:ss.sss': '%Y/%m/%d %H:%M:%S.%f',
    'yyyy/MM/dd-HH:mm:ss.sss': '%Y/%m/%d-%H:%M:%S.%f',
    'yyyy/MM/dd HH:mm:ss': '%Y/%m/%d %H:%M:%S',
    'yyyy/MM/dd-HH:mm:ss': '%Y/%m/%d-%H:%M:%S',
    'yyyy/MM/dd HH:mm': '%Y/%m/%d %H:%M',
    'yyyy/MM/dd-HH:mm': '%Y/%m/%d-%H:%M',
    'yyyy/MM/dd': '%Y/%m/%d',
    'yy/MM/dd HH:mm:ss.sss': '%y/%m/%d %H:%M:%S.%f',
    'yy/MM/dd-HH:mm:ss.sss': '%y/%m/%d-%H:%M:%S.%f',
    'yy/MM/dd HH:mm:ss': '%y/%m/%d %H:%M:%S',
    'yy/MM/dd-HH:mm:ss': '%y/%m/%d-%H:%M:%S',
    'yy/MM/dd HH:mm': '%y/%m/%d %H:%M',
    'yy/MM/dd-HH:mm': '%y/%m/%d-%H:%M',
    'yy/MM/dd': '%y/%m/%d',
    'MM/dd/yyyy HH:mm:ss.sss': '%m/%d/%Y %H:%M:%S.%f',
    'MM/dd/yyyy-HH:mm:ss.sss': '%m/%d/%Y-%H:%M:%S.%f',
    'MM/dd/yyyy HH:mm:ss': '%m/%d/%Y %H:%M:%S',
    'MM/dd/yyyy-HH:mm:ss': '%m/%d/%Y-%H:%M:%S',
    'MM/dd/yyyy HH:mm': '%m/%d/%Y %H:%M',
    'MM/dd/yyyy-HH:mm': '%m/%d/%Y-%H:%M',
    'MM/dd/yyyy': '%m/%d/%Y',
    'MM/dd/yy HH:mm:ss.sss': '%m/%d/%y %H:%M:%S.%f',
    'MM/dd/yy-HH:mm:ss.sss': '%m/%d/%y-%H:%M:%S.%f',
    'MM/dd/yy HH:mm:ss': '%m/%d/%y %H:%M:%S',
    'MM/dd/yy-HH:mm:ss': '%m/%d/%y-%H:%M:%S',
    'MM/dd/yy HH:mm': '%m/%d/%y %H:%M',
    'MM/dd/yy-HH:mm': '%m/%d/%y-%H:%M',
    'MM/dd/yy': '%m/%d/%y',
    'yyyy-MM-ddTHH:mm:ssZ':'%Y-%m-%dT%H:%M:%SZ',
    "yyyy-MM-dd'T'HH:mm:ss.SSS":'%Y-%m-%dT%H:%M:%S.%f',
    "yyyy-MM-ddTHH:mm:ss.SSS":'%Y-%m-%dT%H:%M:%S.%f',
    "HH:mm":"%H:%M",
    'yyyy':'%Y',
    'MM':'%m',
    'dd':'%d',
    'HH':'%H',
    'mm':'%M',
    'ss':'%S'
}
import re
def dt_to_system_format(dateformat_in_user_format):
    format_mapping = {
        "yyyy": "%Y", 
        "yy": "%y",
        "MM": "%m", 
        "dd": "%d",
        "HH": "%H",
        "mm": "%M",
        "ss": "%S",
        "\.SSS": ".%f", "\.sss": ".%f"
    }
    
    for key, value in sorted(format_mapping.items(), key=lambda x: -len(x[0])):
        dateformat_in_user_format = re.sub(key, value, dateformat_in_user_format)
    
    return dateformat_in_user_format
# # Verifying the above datetime conversion function with the manually entered default keys
# correct, incorrect = 0, 0
# for key in datetime_mapping.keys():
#     if datetime_mapping[key]==dt_to_system_format(key):
#         correct += 1
#     else:
#         incorrect += 1
#         print(key, "\t\t", datetime_mapping[key], "\t\t", dt_to_system_format(key))
# print("correct:", correct, "incorrect", incorrect)